### ISSUE TITLE
css modules leak classnames through import statements

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#101]
Assume the following:

kip.css
```css
:root {
  --myvar: 12px;
}
.main { color: red; }
```

floep.css
```css
@import 'kip.css';
.main { background-color: red; font-size: var(--myvar); }
```

floep.js
```jsx
import styles from 'floep.css'

function () {
  return <div className={styles.main}>Floep</div>
}
```

What i would expect is that the text Floep is black (browser default).
What i get is red text.

If I would inspect the styles of my div I would see something like:

```css
// styles                                     source

.kip-main {                                   kip.css
  background-color: red; 
  font-size: 12px;
}

.kip-main {                                   floep.css
  color: red;
}
```

This is not how css modules are supposed work with imports, i believe. I think stuff in `:root` should get imported, but not the classes, etc.?

I believe this is what [compose](https://github.com/css-modules/css-modules#composing-from-other-files) is for.

**Comment by EECOLOR** [comment]
As far as I can tell the [postcss-import plugin](https://github.com/postcss/postcss-import) simply inlines the content of the imported `.css` file. The spec states the following:

> The @import rule allows users to import style rules from other style sheets. If an @import rule refers to a valid stylesheet, user agents must treat the contents of the stylesheet as if they were written in place of the @import rule

In my opinion the css modules in this case acts as a user agent and views the rules as if they are written in place of the import statement. So `floep.css` from your example would be transformed into:

```css
:root {
  --myvar: 12px;
}
.main { color: red; }
.main { background-color: red; font-size: var(--myvar); }
```

This would then be 'modulified', resulting in the behavior you see.

About `composes`, you said:

> I believe this is what compose is for.

I understand your confusion here and I'm having a hard time to understand how these two feature interact. I do know that `@import` is much cleaner to use than `composes` when it comes to variables. `composes` on the other much more clearly indicates the intent of composition.

`@import` is superior when you want to share classes between multiple modules. It's better to do `@import` instead of copying the class names and then `composes` them with the same class names from another file.

I however would personally never use `@import` to do composition.  If I were to import class names I would probably make sure those class names had a distinct name in order to prevent any collisions.

Anyway, I could not find any definitive documentation that states that modules should ignore classes from an imported file.
