### ISSUE TITLE
PostCSS option to prevent hashing classNames

### ISSUE THREAD

**Issue by daveykropf** [kaliberjs/build#20]
In our use case we want to keep the classNames unchanged / unhashed. The generated HTML & CSS code will be exported to a back-end developer, who will implement our code in an external system (Python CMS). Therefor the code needs to be readable. 

Workaround for now:
```css
:global(.Article) {
  width: calc(33.3% - 2rem);
  margin: 1rem;
  background-color: var(--color-background);
}
```
