### ISSUE TITLE
Improvement for `relativeToParent`

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#214]
Using the `.relativeToParent` escape hatch can become quite cumbersome if your component's html is even moderately deep. 

Since allowing an `absolute` element to escape it's parent within 1 component is relatively safe when there's *a* parent within the component that has a `position: relative`, I'd like to ease the rules a bit. What I'm proposing is a similar mechanism we use for state:

```css
.component {
  position: relative;

  & > * > * > .link.relativeToParent {
    positions: static;
  }
}

.link {
  position: relative;

  &.relativeToParent {
    content: '';
    display: block;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}
```

Comparing this to the original, you can see the improvement in readability, while - in my opinion - not sacrificing safety:

```css
.component {
  position: relative;

  & > .content.relativeToParent {
    positions: static;
  }
}

.content {
  position: relative;

  & > .heading.relativeToParent {
    positions: static;
  }
}

.heading {
  position: relative;

  & > .link.relativeToParent {
    positions: static;
  }
}

.link {
  position: relative;

  &.relativeToParent {
    content: '';
    display: block;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}
```
