### ISSUE TITLE
Importing multiple fonts are stripped down to a single import.

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#23]
Font-family imports in the following format:

```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot');
  src: url('webfont.eot?#iefix') format('embedded-opentype'),
       url('webfont.woff2') format('woff2'),
       url('webfont.woff') format('woff'),
       url('webfont.ttf')  format('truetype'),
       url('webfont.svg#svgFontName') format('svg');
}
```

Results in the following output:
```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot');
  src: url('webfont.eot?');
}
```

I guess some loader is modifying urls with some regex which is too aggressive.
