### ISSUE TITLE
CSS loaded from node_modules contains generated classNames from css modules

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#39]
When we import CSS from e.g. the flickity-plugin, all imported css will look like this:
```css
@import 'flickity/dist/flickity.css';

// output
.src-main-entry-flickity-enabled__VJmJc {
  position: relative;
}
.src-main-entry-flickity-enabled__VJmJc:focus { outline: none; }
.src-main-entry-flickity-viewport__2J-Iv {
  overflow: hidden;
  position: relative;
  height: 100%;
}
.src-main-entry-flickity-slider__2VwiQ {
  position: absolute;
  width: 100%;
  height: 100%;
}
// ...
```
