### ISSUE TITLE
Incorrect output using calc() function in .css files

### ISSUE THREAD

**Issue by daveykropf** [kaliberjs/build#95]
input:
```css
:root {
  --transition-duration: 100ms;
}
.myClass {
  transition: visibility calc(var(--transition-duration) + 100);
}
```

Current output (non-valid output) :
```css
.myClass {
  transition: visibility calc(100ms + 100)
}
```

Expected output (valid output): 
```css
.myClass {
  transition: visibility .2s
}

OR 

.myClass {
  transition: visibility calc(100ms + 100ms);
}
```

**Comment by EECOLOR** [comment]
Maybe I'm missing something, but with your input I would guess the output is local. You seem to expect the class to magically add the `ms`.

If you change the `+ 100` part into `+ 100ms` you will probably get the second version of the valid output.

**Comment by daveykropf** [comment]
Well I'm using the same input data in a Wordpress development stack with Webpack (not gulp), which is giving me the correct output.

Input
```css
:root {
  --transition-duration: 100ms;
}
.myClass {
  transition: visibility calc(var(--transition-duration) + 100);
}
```

Output
```css
.myClass {
  transition: visibility .2s
}
```

I've checked it already with Klaas and for now I'm using `+ 100ms`, but Klaas told me to create a bug 😅
